### ISSUE TITLE
Creation of dynamic property Rah_Repeat_Bag::$position is deprecated

### ISSUE THREAD

**Issue by jools-r** [gocom/rah_repeat#1]
Deprecation notice appearing in PHP 8.2.6 and current TXP 4.9-dev.

Defining it at the top of class Rah_Repeat_Bag silences the notice.

**Comment by gocom** [comment]
Thank you for reporting. 🙂

Version 3.0.1 includes a fix https://github.com/gocom/rah_repeat/releases/tag/3.0.1
